name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: bksruuorhvsjghmuoyqi

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.50.3
      - run: supabase -v
      - run: supabase functions deploy telegram-chatgpt-concierge-bot --legacy-build --project-ref $PROJECT_ID --no-verify-jwt
